# Generated by Django 4.1 on 2022-10-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_moviesinfo_link1080p_alter_moviesinfo_link480p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesinfo',
            name='size1080p',
            field=models.CharField(blank=True, default='#', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='moviesinfo',
            name='size480p',
            field=models.CharField(blank=True, default='#', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='moviesinfo',
            name='size720p',
            field=models.CharField(blank=True, default='#', max_length=6, null=True),
        ),
    ]
